name: Ansible-CI
on:
  schedule:
    - cron: '30 5 * * *'
  push:
    branches: ["master"]
    paths:
      - 'docker/**'
      - '.github/workflows/**'
  pull_request:
    branches: ["master"]
    paths:
      - 'docker/**'
      - '.github/workflows/**'

env:
  NAME_TAG: rootshellcoder/ansible:3.11-alpine
  LATEST_TAG: rootshellcoder/ansible:latest

jobs:
  test:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Build Test
        run: docker build -f docker/Dockerfile .

  push:
    needs: [ test ]
    name: Publish to Docker Hub
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker
          push: true
          platforms: linux/amd64,linux/arm64,linux/amd
          tags: |
            ${{ env.LATEST_TAG }}
            ${{ env.NAME_TAG }}

  check:
    needs: [ push ]
    name: Pull image
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Create report file
        run: |
          echo "BUILD TIME" > version.txt
          date +%s >> version.txt
          echo "---" >> version.txt
      - name: Check version
        run: |
          docker pull ${{ env.LATEST_TAG }}
          echo "- PYTHON3 VERSION"  >> version.txt
          docker run -i --rm  ${{ env.LATEST_TAG }} python3 --version >> version.txt
          echo "- ANSIBLE VERSION"  >> version.txt
          docker run -i --rm  ${{ env.LATEST_TAG }} ansible --version >> version.txt
          echo "- ANSIBLE LINT"  >> version.txt
          docker run -i --rm  ${{ env.LATEST_TAG }} ansible-lint --version >> version.txt
          echo "- ANSIBLE GALAXY"  >> version.txt
          docker run -i --rm  ${{ env.LATEST_TAG }} ansible-galaxy --version >> version.txt
          echo "- ANSIBLE CONNECTION"  >> version.txt
          docker run -i --rm  ${{ env.LATEST_TAG }} ansible-connection --version >> version.txt
          echo "- ANSIBLE VAULT"  >> version.txt
          docker run -i --rm  ${{ env.LATEST_TAG }} ansible-vault --version >> version.txt
          echo "- ANSIBLE COMMUNITY"  >> version.txt
          docker run -i --rm  ${{ env.LATEST_TAG }} ansible-community --version >> version.txt
          echo "- ANSIBLE-GALAXY COLLECTION"  >> version.txt
          docker run -i --rm  ${{ env.LATEST_TAG }} ansible-galaxy collection list >> version.txt
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: RootShell-coder
          author_email: Root.Shelling@gmail.com
          message: 'upd'
          add: 'version*'
