name: Ansible-CI
on:
  schedule:
    - cron: '30 5 * * *'
  push:
    branches: ["master"]
    paths:
      - 'docker/**'
  pull_request:
    branches: ["master"]
    paths:
      - 'docker/**'

env:
  IMAGE_NAME: ansible

jobs:
  test:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Build Test
        run: docker build -f docker/Dockerfile .

  push:
    needs: [ test ]
    name: Publish to Docker Hub
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USER }}/${IMAGE_NAME}:${GITHUB_SHA::5} -f docker/Dockerfile .
          docker tag ${{ secrets.DOCKERHUB_USER }}/${IMAGE_NAME}:${GITHUB_SHA::5} ${{ secrets.DOCKERHUB_USER }}/${IMAGE_NAME}:latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
      - name: Push Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/${IMAGE_NAME}:${GITHUB_SHA::5}
          docker push ${{ secrets.DOCKERHUB_USER }}/${IMAGE_NAME}:latest
      - name: Delete images
        run: |
          docker rmi ${{ secrets.DOCKERHUB_USER }}/${IMAGE_NAME}:${GITHUB_SHA::5}
          docker rmi ${{ secrets.DOCKERHUB_USER }}/${IMAGE_NAME}:latest

  check:
    needs: [ push ]
    name: Pull image
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Check version
        run: |
          docker pull ${{ secrets.DOCKERHUB_USER }}/${IMAGE_NAME}:latest
          docker run -i --rm  ${{ secrets.DOCKERHUB_USER }}/${IMAGE_NAME}:latest ansible --version > version.txt
          docker run -i --rm  ${{ secrets.DOCKERHUB_USER }}/${IMAGE_NAME}:latest ansible-lint --version >> version.txt
      - name: Create report file
        run: |
          echo "" >> version.txt
          date +%s >> version.txt
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: RootShell-coder
          author_email: Root.Shelling@gmail.com
          message: 'upd'
          add: 'version*'
